const { Gear } = require('../models');

const geardata = [
    {
        product_name: 'Nikon Z9 Mirrorless Body',
        description: "Meet the unstoppable Nikon Z 9. The flagship mirrorless camera built for pros, with Nikon's most powerful autofocus, groundbreaking 8K video, blazing fast 120 fps stills, stunning 45.7MP images, the world's first truly blackout free viewfinder, and Nikon's first 4-axis tilting touchscreen. All in the most intelligent, durable, comfortable and connected Nikon camera the world has ever seen.",
        image_url: 'Nikon Z9 Mirrorless Body.webp',
        cost_per_day: 350.00,
        category: 'BODY',
        available: true,
        owner_id: 1,
    },
    {
        product_name: 'Panasonic GH6 Camera Body',
        description: "The LUMIX GH6 with a 25.2-MP Live MOS Sensor without LPF (low-pass filter) increases effective pixel count by more than 20% for high-resolution, high-speed signal readout and wide dynamic range. The image processor with doubled processing speed integrates New Intelligent Detail Processing, New 2D Noise Reduction, and High Precision 3D Noise Reduction for video.",
        image_url: 'Panasonic GH6 Camera Body.webp',
        cost_per_day: 145.00,
        category: 'BODY',
        available: true,
        owner_id: 1,
    },
    {
        product_name: 'Nikon NIKKOR Z 400mm f/4.5 VR S Lens',
        description: "Travel light and move fast. Comfortably shoot handheld with unwavering accuracy. Capture the sharpness and beautiful bokeh only a prime lens can deliver. The NIKKOR Z 400mm f/4.5 VR S is the super-telephoto prime for those who use agility and speed to nail decisive views of birds, wildlife, sports and aircraft.",
        image_url: 'Nikon NIKKOR Z 400mm f4.5 VR S Lens.webp',
        cost_per_day: 65.00,
        category: 'LENSES',
        available: true,
        owner_id: 1,
    },
    {
        product_name: 'Panasonic Leica DG Summilux 25mm f/1.4',
        description: "Panasonic's Leica DG Summilux 25 mm f/1.4 ASPH Micro 4/3 lens is designed for use with Lumix G Micro 4/3 cameras. It provides an angle of view similar to a 50mm lens on a 35mm or full-frame digital camera, and the wide f/1.4 maximum aperture can deliver beautiful, bright photos and videos with softly out-of-focus backgrounds. Built to Leica's usual high standards, this lens delivers excellent image quality with minimal distortion or chromatic aberrations, with a sturdy metal mount.",
        image_url: 'Panasonic Leica DG Summilux 25mm f1.4.webp',
        cost_per_day: 28.00,
        category: 'LENSES',
        available: true,
        owner_id: 1,
    },
    {
        product_name: 'Sony Alpha A7IV Mirrorless Body',
        description: "Prepare to be inspired. The α7 IV's true-to-life resolution and remarkable AI-powered autofocus complement a range of world-class features at the cutting edge of imaging technology. Go beyond basic with 33-Megapixel1 full-frame sensor for outstanding still image and 4K11 movie quality. The a7IV boasts a new and improved AF, and while there is a myriad of other improvements, the focus breathing compensation is a truly unique new feature. Along with other major movie technology innovations; S-Cinematone 4K60p XAVCS-I, 7K oversampling, AF assist, focus map, heat dissipating structure, optical active mode stabilization and more.",
        image_url: 'Sony Alpha A7IV Mirrorless Body.webp',
        cost_per_day: 185.00,
        category: 'BODY',
        available: true,
        owner_id: 2,
    },
    {
        product_name: 'Sony SEL FE PZ 16-35mm f/4.0 Lens',
        description: "FE PZ 16-35mm F4 G - Sony Alpha full-frame constant-aperture wide-angle G lens with power zoom provided by XD linear motors and next-generation autofocus performance optimized for still and movie.",
        image_url: 'Sony SEL FE PZ 16-35mm f4.0 Lens.webp',
        cost_per_day: 45.00,
        category: 'LENSES',
        available: true,
        owner_id: 2,
    },
    {
        product_name: 'Profoto A10 Off-Camera Kit - Sony',
        description: "Its round head delivers light that's both natural and beautiful with a soft smooth fall-off. And it's incredibly easy and to use, with superfast recycling and a long-lasting battery, so you'll never miss a shot. And with Profoto's latest Bluetooth enabled technology AirX built in, you can unleash the full power of the A10 when shooting with your smartphone. So regardless of what type of camera you use, you'll now have access to light shaping excellence anytime, anywhere, always.",
        image_url: 'Profoto A10 Off-Camera Kit - Sony.webp',
        cost_per_day: 40.00,
        category: 'FLASH',
        available: true,
        owner_id: 2,
    },
    {
        product_name: 'Godox AD600 Pro TTL Studio Flash',
        description: "AD600Pro All-in-One Outdoor Flash has 600Ws strong power, 0.01~0.9s recycle time, 12 continuous flashes in 1/16 power output, 38W LED modeling lamp, 360 full power pops, stable colour temperature (changes within ±75K over the entire power range in colour temperature mode). It is compatible with TTL auto flash systems of multi-brand cameras.",
        image_url: 'Godox AD600 Pro TTL Studio Flash.webp',
        cost_per_day: 50.00,
        category: 'FLASH',
        available: true,
        owner_id: 2,
    },
    {
        product_name: 'Canon EOS R6 MKII Full Frame Camera',
        description: "Introducing a standard full-frame camera evolved with hybrid features for still and movie shooting. The EOS R6 Mark II enables various photographic expressions that transcend boundaries between recording personal life and professional production purposes, as well as between photo shooting and movie shooting. Achieve creativity in everyday life with the EOS R6 Mark II.",
        image_url: 'Canon EOS R6 MKII Full Frame Camera.webp',
        cost_per_day: 200.00,
        category: 'BODY',
        available: true,
        owner_id: 3,
    },
    {
        product_name: 'Canon EOS R5 C w/ Cage & V-Mount Kit',
        description: "The Canon EOS R5 C is a professional hybrid cinema camera, designed for solo operators that require a one-stop solution for their production needs. It combines the professional filmmaking features expected from a Cinema EOS camera with the powerful photographic capabilities of the EOS R System. Compact and lightweight, the EOS R5 C is a true hybrid camera, boasting many of the video formats and features from the Cinema EOS lineup as well as many of the still-imaging capabilities of the EOS R5 camera in a beautifully designed body.",
        image_url: 'Canon EOS R5 C w/ Cage & V-Mount Kit.webp',
        cost_per_day: 345.00,
        category: 'BODY',
        available: true,
        owner_id: 3,
    },
    {
        product_name: 'Aputure LS 600X Pro V-mount Kit',
        description: "The Light Storm 600x Pro is the newest member of the Aputure LS 600 series of point-source LEDs, featuring a 600W bi-colour chipset with precision colour blending optical design. It harnesses the form factor and design of the LS 600d Pro, the same control box interface, and Bowens Mount compatibility while introducing a 2700K to 6500K variable CCT range and maintaining an output of 18,510 lux at 3m with the F10 Fresnel.",
        image_url: 'Aputure LS 600X Pro V-mount Kit.webp',
        cost_per_day: 210.00,
        category: 'LIGHTS',
        available: true,
        owner_id: 4,
    },
    {
        product_name: 'Nanlux Evoke 1200B LED Spotlight',
        description: "Evoke 1200B offers impeccable light quality in the same category by adapting 2x1200W Bi-colour LED chips in Dot Matrix format. It features higher light efficiency with luminance level at 5600K up to 61,030lux@3m 5600K(with reflector RF-NLM-26), comparable to that of a 1.8kW PAR or 2.5kW HMI Fresnel. Sufficient illumination is also guaranteed for shooting Ultra-High-Speed without worrying about flicker in uplifting the frame rate. Way more flexibility in creation by simulating natural light from sunrise to daylight to sunset is offered by Evoke 1200B's variable CCT range of 2,700K to 6,500K.",
        image_url: 'Nanlux Evoke 1200B LED Spotlight.webp',
        cost_per_day: 200.00,
        category: 'LIGHTS',
        available: true,
        owner_id: 4,
    },
    {
        product_name: 'Aputure LS 60X Bi-Color LED Light',
        description: "The Light Storm 60x is an expanded bi-colour (2700K~6500K) adjustable focusing LED light, which uses precision condenser lens optics to allow users to internally adjust the spot/flood beam angle between 15°~45°.",
        image_url: 'Aputure LS 60X Bi-Color LED Light.webp',
        cost_per_day: 65.00,
        category: 'LIGHTS',
        available: true,
        owner_id: 4,
    },
    
];

const seedGear = () => Gear.bulkCreate(geardata, {
    individualHooks: true,
    returning: true,
});

module.exports = seedGear;
